version: '3.7'

services:
  nginx-rmtp:
    image: alqutami/rtmp-hls:latest-alpine
    container_name: rtmp-hls
    restart: always
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./conf/blocklist.conf:/etc/nginx/blocklist.conf
      - ./conf/nginx-acl.conf:/etc/nginx/nginx.conf
      - ./media:/mnt
      - ./custom-players:/usr/local/nginx/html/players
    ports:
      - 1935:1935
      - 8080:8080
